apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zylp89x41-nodejs
  janus-idp.io/tekton: zylp89x41-nodejs
  backstage.io/kubernetes-id: zylp89x41-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zylp89x41-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
